
"use client";

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { BarChartHorizontal, Calendar as CalendarIcon, Loader2, FileText, CheckCircle, AlertTriangle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Calendar } from '@/components/ui/calendar';
import { useToast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';
import { format } from 'date-fns';
import { generateReportAction, type ReportState } from './actions';
import { Separator } from '@/components/ui/separator';

export default function ReportsPage() {
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<ReportState | null>(null);
  const [date, setDate] = useState<Date>(new Date());

  const handleGenerateReport = async () => {
    setLoading(true);
    setResult(null);

    const reportDate = date || new Date();
    const input = {
      month: reportDate.getMonth(),
      year: reportDate.getFullYear(),
    };

    const res = await generateReportAction(input);
    if (res.error) {
      toast({ title: "Error", description: res.error, variant: "destructive" });
    } else {
      setResult(res);
    }
    setLoading(false);
  };
  
  const formatCurrency = (amount: number, currencyCode: string = 'KES') => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: currencyCode,
    }).format(amount);
  };

  return (
    <div className="flex-1 space-y-4 p-4 md:p-8 pt-6">
      <div className="flex items-center gap-4">
        <BarChartHorizontal className="h-8 w-8" />
        <h2 className="text-3xl font-bold tracking-tight">AI-Powered Reports</h2>
      </div>

      <div className="grid gap-8 md:grid-cols-5">
        <div className="md:col-span-2 lg:col-span-2">
            <Card>
                <CardHeader>
                    <CardTitle>Generate a Report</CardTitle>
                    <CardDescription>Select a month to generate a performance report with AI insights.</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                    <div className="space-y-2">
                        <Popover>
                            <PopoverTrigger asChild>
                            <Button
                                variant={"outline"}
                                className={cn(
                                "w-full justify-start text-left font-normal",
                                !date && "text-muted-foreground"
                                )}
                            >
                                <CalendarIcon className="mr-2 h-4 w-4" />
                                {date ? format(date, "MMMM yyyy") : <span>Pick a month</span>}
                            </Button>
                            </PopoverTrigger>
                            <PopoverContent className="w-auto p-0">
                            <Calendar
                                mode="single"
                                selected={date}
                                onSelect={(d) => setDate(d || new Date())}
                                initialFocus
                                captionLayout="dropdown-buttons"
                                fromYear={2020}
                                toYear={new Date().getFullYear()}
                            />
                            </PopoverContent>
                        </Popover>
                    </div>
                    <Button onClick={handleGenerateReport} disabled={loading} className="w-full">
                        {loading ? <Loader2 className="animate-spin" /> : 'Generate Report'}
                    </Button>
                </CardContent>
            </Card>
        </div>

        <div className="md:col-span-3 lg:col-span-3">
          <Card className="min-h-[400px]">
            <CardHeader>
              <CardTitle>{result?.report?.reportTitle || 'Monthly Report'}</CardTitle>
              <CardDescription>
                {result?.report ? 'Generated by AI' : 'Your generated report will appear here.'}
              </CardDescription>
            </CardHeader>
            <CardContent>
                {loading && <div className="flex justify-center items-center p-16"><Loader2 className="h-10 w-10 animate-spin text-primary" /></div>}
                
                {result?.report && (
                    <div className="space-y-6">
                        <p className="text-muted-foreground italic">{result.report.summary}</p>
                        
                        <Separator />
                        
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-center">
                            <div>
                                <p className="text-xs text-muted-foreground">Total Revenue</p>
                                <p className="text-lg font-bold">{formatCurrency(result.report.totalRevenue)}</p>
                            </div>
                            <div>
                                <p className="text-xs text-muted-foreground">Occupancy</p>
                                <p className="text-lg font-bold">{result.report.occupancyRate.toFixed(1)}%</p>
                            </div>
                            <div>
                                <p className="text-xs text-muted-foreground">Late Payments</p>
                                <p className="text-lg font-bold">{result.report.latePayments}</p>
                            </div>
                            <div>
                                <p className="text-xs text-muted-foreground">Maint. Requests</p>
                                <p className="text-lg font-bold">{result.report.newMaintenanceRequests}</p>
                            </div>
                        </div>

                        <Separator />

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                            <div>
                                <h4 className="font-semibold flex items-center gap-2 mb-2"><CheckCircle className="h-4 w-4 text-green-500"/> Highlights</h4>
                                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                                    {result.report.highlights.map((item, i) => <li key={i}>{item}</li>)}
                                </ul>
                            </div>
                            <div>
                                <h4 className="font-semibold flex items-center gap-2 mb-2"><AlertTriangle className="h-4 w-4 text-yellow-500"/> Areas for Improvement</h4>
                                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                                    {result.report.areasForImprovement.map((item, i) => <li key={i}>{item}</li>)}
                                </ul>
                            </div>
                        </div>
                    </div>
                )}
                
                {!loading && !result && (
                    <div className="text-center text-muted-foreground pt-16 flex flex-col items-center">
                        <FileText className="h-12 w-12 mb-4" />
                        <p>Select a month and click "Generate Report" to begin.</p>
                    </div>
                )}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
